name: On Push

on:
  push:
    branches: [main]

jobs:
  build-vst3:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        shell: bash
        run: ./generate.sh

      - name: Build Debug
        shell: bash
        run: ./build_debug.sh

  build-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Generate
        shell: bash
        run: ./generate_ios.sh

      - name: Build iOS
        shell: bash
        run: ./build_debug.sh
